# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.2.0"

default_platform :ios


platform :ios do

  before_all do
    #unit_tests Commented out temporarily. Will be un-commented when we develop tests regularly.
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120"
    ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "1"

    # increment_build_number

    # xctool # run the tests of your app
  end

  desc "Unit Tests"
  lane :unit_tests do
    #run_tests(scheme: "ios-boilerplateTests")
  end

  desc "Export a new version as .ipa and .xcarchive"
  lane :build_development do
    clean_build_artifacts

    # disable automatic code signing
    disable_automatic_code_signing


    gym(
      clean: true,
      workspace: "ios-boilerplate.xcworkspace",
      scheme: "ios-boilerplate",
      output_directory: "build/",
      output_name: "ios-boilerplate",
      configuration: "Development",
      archive_path: "build/ios-boilerplate",
      xcargs: "CODE_SIGNING_ALLOWED=NO",
      export_method: "development"
    )

    backup_xcarchive(
      xcarchive: "build/ios-boilerplate.xcarchive",
      destination: "build/",
      versioned: false
    )

  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    update_sslPinning(
      sslPinningEnabled: true
    )
  end


  private_lane :reset_badges do |options|
    Dir.chdir ".." do
      sh "git checkout -- *.xcassets/*"
    end
  end
end

# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
