name: main-workflow

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  jazzy-generator:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - uses: grkmndr/jazzy-doc-generation-action@v1.1
      with:
        config: .jazzy.yaml

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Jazzy documentation updated.